using SQLite;

namespace RetroFootballManager.Models
{
    // A single fixture in the schedule. The complete fixture list (home and away round,
    // everyone against everyone) is generated by the FixtureGenerator at season start.
    public class Fixture
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        public int Season { get; set; }

        [Indexed]
        public int LeagueTier { get; set; }

        // Matchday 1..34 (with 18 teams).
        public int Matchday { get; set; }

        public DateTime Date { get; set; }

        [Indexed]
        public int HomeTeamId { get; set; }

        [Indexed]
        public int AwayTeamId { get; set; }

        public bool Played { get; set; }

        public int HomeGoals { get; set; }
        public int AwayGoals { get; set; }

        // Friendly (M7): playable like a real match, but with no effect on the standings/
        // season stats - CalendarService/StandingsCalculator filter accordingly.
        public bool IsFriendly { get; set; }

        // Prevents duplicate analyst preview messages when the main menu is visited multiple
        // times before the same due match (see PreMatchAnalysisService/MainMenuViewModel).
        public bool AnalysisSent { get; set; }
    }
}
