namespace RetroFootballManager.Common
{
    public static class ClubNameGenerator
    {
        public const int ClubsPerTier = 18;
        public const int TierCount = 4;

        // LogoFile = filename under Resources/Images/Logos/ (null = no crest set yet,
        // UI shows the abbreviation placeholder instead).
        public static IReadOnlyList<(string Name, string ShortName, int Tier, string? LogoFile)> FixedRoster { get; } =
        [
            ("FC Adlerbach", "ADL", 1, "adlerbach.png"),
            ("SV Nordstedt", "NOR", 1, "nordstedt.png"),
            ("VfL Rheinau", "RHE", 1, "rheinau.png"),
            ("SC Falkenberg", "FAL", 1, "falkenberg.png"),
            ("TSV Hohenfeld", "HOH", 1, "hohenfeld.png"),
            ("1. FC Grünwalde", "GRÜ", 1, "gruenwalde.png"),
            ("VfB Sonnborn", "SON", 1, "sonnborn.png"),
            ("SpVgg Talheim", "TAL", 1, "talheim.png"),
            ("FSV Königsbrück", "KÖN", 1, null),
            ("Borussia Marktstetten", "MAR", 1, null),
            ("SG Lindenau", "LIN", 1, null),
            ("SSV Eichwald", "EIC", 1, null),
            ("BSV Westerholt", "WES", 1, null),
            ("FC Steinbach", "STE", 1, null),
            ("SV Altenburg", "ALT", 1, null),
            ("VfL Neustadt", "NEU", 1, null),
            ("SC Bergheim", "BER", 1, null),
            ("TSV Seelund", "SEE", 1, null),

            ("1. FC Weißenfels", "WEI", 2, null),
            ("VfB Rosental", "ROS", 2, null),
            ("SpVgg Elbstedt", "ELB", 2, null),
            ("FSV Moorbach", "MOO", 2, null),
            ("Borussia Kaltenkirch", "KAL", 2, null),
            ("SG Wiesengrund", "WIE", 2, null),
            ("SSV Dornheim", "DOR", 2, null),
            ("BSV Erlenbach", "ERL", 2, null),
            ("FC Buchholz", "BUC", 2, null),
            ("SV Sandhofen", "SAN", 2, null),
            ("VfL Birkenau", "BIR", 2, null),
            ("SC Freiberg", "FRE", 2, null),
            ("TSV Hafenstadt", "HAF", 2, null),
            ("1. FC Silberbach", "SIL", 2, null),
            ("VfB Ostmark", "OST", 2, null),
            ("SpVgg Waldkirch", "WAL", 2, null),
            ("FSV Blaufeld", "BLA", 2, null),
            ("Borussia Rautenberg", "RAU", 2, null),

            ("SG Görwitz", "GÖR", 3, null),
            ("SSV Lehmgrube", "LEH", 3, null),
            ("BSV Schönau", "SCH", 3, null),
            ("FC Tannheim", "TAN", 3, null),
            ("SV Kupferberg", "KUP", 3, null),
            ("VfL Mühlbach", "MÜH", 3, null),
            ("SC Hinterbrück", "HIN", 3, null),
            ("TSV Eisenfurt", "EIS", 3, null),
            ("1. FC Brunnenfeld", "BRU", 3, null),
            ("VfB Hochried", "HOC", 3, null),
            ("SpVgg Schattenwald", "SCH", 3, null),
            ("FSV Dunkelau", "DUN", 3, null),
            ("Borussia Felsenheim", "FEL", 3, null),
            ("SG Wolfsbronn", "WOL", 3, null),
            ("SSV Klarenthal", "KLA", 3, null),
            ("BSV Bergstetten", "BER", 3, null),
            ("FC Sonnenried", "SON", 3, null),
            ("SV Eibenstadt", "EIB", 3, null),

            ("VfL Mooswinkel", "MOO", 4, "mooswinkel.png"),
            ("SC Rabenfels", "RAB", 4, "rabenfels.png"),
            ("TSV Kornstedt", "KOR", 4, "kornstedt.png"),
            ("1. FC Hügelheim", "HÜG", 4, "huegelheim.png"),
            ("VfB Tiefenbronn", "TIE", 4, "tiefenbronn.png"),
            ("SpVgg Waldstetten", "WAL", 4, "waldstetten.png"),
            ("FSV Ehrental", "EHR", 4, "ehrental.png"),
            ("Borussia Brandau", "BRA", 4, "brandau.png"),
            ("SG Hohenbronn", "HOH", 4, "hohenbronn.png"),
            ("SSV Schieferstadt", "SCH", 4, "schieferstadt.png"),
            ("BSV Eisengrund", "EIS", 4, "eisengrund.png"),
            ("FC Buchenfeld", "BUC", 4, "buchenfeld.png"),
            ("SV Rosenhügel", "ROS", 4, "rosenhuegel.png"),
            ("VfL Sturmhain", "STU", 4, "sturmhain.png"),
            ("SC Nebeltal", "NEB", 4, "nebeltal.png"),
            ("TSV Farnheim", "FAR", 4, "farnheim.png"),
            ("1. FC Kieselbrück", "KIE", 4, "kieselbrueck.png"),
            ("VfB Wetterau", "WET", 4, "wetterau.png"),
        ];
    }
}
